version: "3.7"

services:

  app_proxy:
    environment:
      APP_HOST: xteve_xteve_1
      APP_PORT: 34400 

  xteve:
    image: dnsforge/xteve:latest 
    container_name: xteve 
    user: "1000:1000" 
    init: true
    ports:
      - "34400:34400"
    volumes:
      - ${APP_DATA_DIR}/config:/config
      - ${APP_DATA_DIR}/data:/tmp/xteve
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Santo_Domingo 
    restart: unless-stopped